export enum navItems {
  Dashboard = "Dashboard",
  User = "User",
  Ecommerce = "Ecommerce",
  ClientFacing = "Client Facing",
  Products = "Products",
  Customers = "Customers",
  Orders = "Orders",
  Geography = "Geography",
  SalesCharts = "Sales charts",
  Overview = "Overview",
  Daily = "Daily",
  Monthly = "Monthly",
  Breakdown = "Breakdown",
  Management = "Management",
  Admin = "Admin",
  Performance = "Performance",
}
